### PR TITLE
fixing "Program Output:" issue

### LINKED ISSUE #17: Display execution output without `Program Output: `
Use `cairo_runner.write_output()` to display the execution output on stdout.
Right now we use
```
cairo_run::write_output(&mut cairo_runner).map_err(|e| {
			format!(
				"failed to print the program output \"{}\": {}",
				self.program.display(),
				e,
			)
		})?;
```
that prepend the program output with a `Program Output: ` line. A line we don't want for our own output

### PR DESCRIPTION
**Pull request by gdnathan**
close #17

### CODE REVIEW

**Comment by gdnathan** [comment]
Using ``cairo_runner.write_output()`` wasn't enough, i had to stip the ``Program Output:`` myself.

the private function ``print_program_output`` is to avoid multiple ``map_err`` with ``format!`` macro, and reduce code.

**Review by tdelabro — CHANGES_REQUESTED** [review]
Cargo.lock made you use an outdated version of the library.
Upgrade Cleaopatra to its latest version and you should be able to use the function as described in the issue.

**Comment by gdnathan** [comment]
Ok, i updated Cleopatra and changed to the function described in the issue.

Upgrading also made a change to `cairo_run` that now [take 4 parameters instead of 1](https://github.com/lambdaclass/cleopatra_cairo/blob/8328185a3b8edd6d34dc33fe2e9e1d8854c2a470/src/cairo_run.rs#L10). Tell me if the values i used are right.

**Review by tdelabro — APPROVED** [review]
just rebase and run `cargo +nightly fmt`
Then I will merge

**Pull request merged**
